### ISSUE TITLE
Documentation to use the package

### ISSUE THREAD

**Issue by Alosies** [woss/graphql-to-sql#2]
Hi, 

Looks like this package can do wonders to someone trying to migrate from Prisma to Hasura. But I'm not able to understand how exactly to use this package. Could you please update the docs

**Comment by woss** [comment]
hi, uh, i didn't maintain this for long time and prisma and hasura advanced so most probably this package is deprecated. 

I'll make the notice here that this is not maintained. 
i suggest considering the [Postgraphile](https://www.graphile.org/postgraphile/)
